// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    return $.getJSON("recipe.json", function(recipe) {
      return $("body").append([
        $("<h1>").text(recipe.title), $("<h2>").text("Ingredients"), $("<ul>").append((function() {
          var i, _i, _len, _ref, _results;
          _ref = recipe.ingredients;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            i = _ref[_i];
            _results.push($("<li>").text(i.quantity + " of " + i.thing));
          }
          return _results;
        })()), $("<h2>").text("Steps"), $("<ul>").append((function() {
          var i, _i, _len, _ref, _results;
          _ref = recipe.steps;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            i = _ref[_i];
            _results.push($("<li>").text(i));
          }
          return _results;
        })())
      ]);
    });
  });

}).call(this);
